Repository SWM-E2I/wemeet-backend, pull requests merged in 2023-07, with the labels that each got.

#39 feat(docs): add OpenApi specification for api documentation
  build.gradle
  src/main/java/com/e2i/wemeet/config/docs/StaticRoutingConfiguration.java
  src/main/java/com/e2i/wemeet/config/security/config/SecurityConfig.java
  src/main/java/com/e2i/wemeet/config/security/filter/RefreshTokenProcessingFilter.java
  src/main/java/com/e2i/wemeet/controller/GlobalExceptionController.java
  src/main/java/com/e2i/wemeet/controller/swagger/SwaggerUiController.java
  src/main/java/com/e2i/wemeet/dto/request/LoginRequestDto.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
  src/main/resources/static/dist/favicon-16x16.png
  src/main/resources/static/dist/favicon-32x32.png
  src/main/resources/static/dist/index.css
  src/main/resources/static/dist/swagger-initializer.js
  src/main/resources/static/dist/swagger-ui-bundle.js
  src/main/resources/static/dist/swagger-ui-bundle.js.map
  src/main/resources/static/dist/swagger-ui-standalone-preset.js
  src/main/resources/static/dist/swagger-ui-standalone-preset.js.map
  src/main/resources/static/dist/swagger-ui.css
  src/main/resources/static/dist/swagger-ui.css.map
  src/main/resources/static/dist/swagger-ui.html
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/main/resources/static/swagger-ui/sampleAuth.yaml
  src/test/java/com/e2i/wemeet/config/security/filter/RefreshTokenProcessingFilterTest.java
  src/test/java/com/e2i/wemeet/config/security/filter/SMSLoginProcessingFilterTest.java
  src/test/java/com/e2i/wemeet/controller/GlobalExceptionControllerTest.java
  src/test/java/com/e2i/wemeet/controller/admin/TestTokenInjectionControllerTest.java
  src/test/java/com/e2i/wemeet/controller/credential/CredentialControllerTest.java
  src/test/java/com/e2i/wemeet/support/config/AbstractIntegrationTest.java
Labels: 📚 docs

#42 build(gradle): add queryDsl settings
  build.gradle
  src/main/java/com/e2i/wemeet/config/common/JpaConfig.java
Labels: 🖌 chore

#47 refactor(code): separate find code funtion to code servie
  src/main/java/com/e2i/wemeet/controller/member/MemberController.java
  src/main/java/com/e2i/wemeet/service/code/CodeService.java
  src/main/java/com/e2i/wemeet/service/code/CodeServiceImpl.java
  src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
  src/test/java/com/e2i/wemeet/service/code/CodeServiceTest.java
Labels: 💻 test, 🛠 refactor

#51 refactor(api-docs): change api docs tag
  src/test/java/com/e2i/wemeet/config/security/filter/SMSLoginProcessingFilterTest.java
  src/test/java/com/e2i/wemeet/controller/credential/CredentialControllerTest.java
  src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
Labels: 🛠 refactor

#50 feat(team): add cru api
  src/main/java/com/e2i/wemeet/controller/GlobalExceptionController.java
  src/main/java/com/e2i/wemeet/controller/team/TeamController.java
  src/main/java/com/e2i/wemeet/domain/code/CodePk.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/domain/team/AdditionalActivity.java
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/domain/teampreferencemeetingtype/TeamPreferenceMeetingType.java
  src/main/java/com/e2i/wemeet/domain/teampreferencemeetingtype/TeamPreferenceMeetingTypeRepository.java
  src/main/java/com/e2i/wemeet/dto/request/team/CreateTeamRequestDto.java
  src/main/java/com/e2i/wemeet/dto/request/team/ModifyTeamRequestDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/MyTeamDetailResponseDto.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/badrequest/BadRequestException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/TeamAlreadyExistsException.java
  src/main/java/com/e2i/wemeet/exception/unauthorized/UnAuthorizedUnivException.java
  src/main/java/com/e2i/wemeet/service/team/TeamService.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/main/resources/db/migration/V2306210150__create_member.sql
  src/main/resources/db/migration/V2306211524__create_team.sql
  src/main/resources/db/migration/V2307112347__create_teamPreferenceMeetingType.sql
  src/main/resources/db/migration/V2307130221__insert_code_data.sql
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
  src/test/java/com/e2i/wemeet/support/fixture/MemberFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
Labels: ✨ feat

#54 feat(member): add get member role api
  src/main/java/com/e2i/wemeet/controller/member/MemberController.java
  src/main/java/com/e2i/wemeet/dto/response/member/RoleResponseDto.java
  src/main/java/com/e2i/wemeet/service/member/MemberService.java
  src/main/java/com/e2i/wemeet/service/member/MemberServiceImpl.java
  src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
  src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java
Labels: ✨ feat

#55 feat(team): add team invitation api
  src/main/java/com/e2i/wemeet/controller/team/TeamController.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/domain/member/MemberRepository.java
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/domain/team/TeamRepository.java
  src/main/java/com/e2i/wemeet/domain/team/invitation/InvitationAcceptStatus.java
  src/main/java/com/e2i/wemeet/domain/team/invitation/TeamInvitation.java
  src/main/java/com/e2i/wemeet/domain/team/invitation/TeamInvitationRepository.java
  src/main/java/com/e2i/wemeet/dto/request/team/InviteTeamRequestDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamManagementResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamMemberResponseDto.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/badrequest/GenderNotMatchException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/InvitationAlreadyExistsException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/InvitationAlreadySetException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/NotBelongToTeamException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/TeamAlreadyActiveException.java
  src/main/java/com/e2i/wemeet/exception/notfound/InvitationNotFoundException.java
  src/main/java/com/e2i/wemeet/service/team/TeamService.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/main/resources/db/migration/V2306211524__create_team.sql
  src/main/resources/db/migration/V2307142217__create_team_invitation.sql
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/config/security/manager/CreditAuthorizationManagerTest.java
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
  src/test/java/com/e2i/wemeet/support/fixture/CollegeInfoFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/MemberFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
Labels: ✨ feat

#56 feat(team): add team delete api
  src/main/java/com/e2i/wemeet/controller/team/TeamController.java
  src/main/java/com/e2i/wemeet/domain/teampreferencemeetingtype/TeamPreferenceMeetingType.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/badrequest/ManagerSelfDeletionException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/NonTeamMemberException.java
  src/main/java/com/e2i/wemeet/service/team/TeamService.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/main/resources/db/migration/V2306211524__create_team.sql
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
Labels: ✨ feat

#66 refactor(team): change teamCode format
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamManagementResponseDto.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/main/resources/db/migration/V2306211524__create_team.sql
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
Labels: 🛠 refactor

#63 refactor(profileImage): set profile image file extension to jpg
  src/main/java/com/e2i/wemeet/service/profileimage/ProfileImageServiceImpl.java
Labels: 🛠 refactor

#58 build(gradle): modify container image tag
  .github/workflows/cd.yml
  build.gradle
Labels: 🚀 build

#67 refactor(team): refactoring TeamService
  src/main/java/com/e2i/wemeet/controller/team/TeamController.java
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/domain/team/invitation/TeamInvitation.java
  src/main/java/com/e2i/wemeet/service/team/TeamInvitationService.java
  src/main/java/com/e2i/wemeet/service/team/TeamInvitationServiceImpl.java
  src/main/java/com/e2i/wemeet/service/team/TeamService.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamInvitationServiceTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
Labels: 🛠 refactor

#71 refactor(member): modify createMember api
  src/main/java/com/e2i/wemeet/controller/member/MemberController.java
  src/main/java/com/e2i/wemeet/domain/member/Mbti.java
  src/main/java/com/e2i/wemeet/dto/request/member/CreateMemberRequestDto.java
  src/main/java/com/e2i/wemeet/dto/request/member/ModifyMemberRequestDto.java
  src/main/java/com/e2i/wemeet/dto/response/member/MemberDetailResponseDto.java
  src/main/java/com/e2i/wemeet/service/aws/ses/AwsSesService.java
  src/main/java/com/e2i/wemeet/service/member/MemberService.java
  src/main/java/com/e2i/wemeet/service/member/MemberServiceImpl.java
  src/main/java/com/e2i/wemeet/util/aspect/TokenInjectionAspect.java
  src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
  src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java
  src/test/java/com/e2i/wemeet/support/fixture/MemberFixture.java
  src/test/java/com/e2i/wemeet/util/aspect/TokenInjectionAspectTest.java
Labels: 🛠 refactor

#75 refactor(entity): change entity fields type and add delete column
  src/main/java/com/e2i/wemeet/config/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/e2i/wemeet/controller/GlobalExceptionController.java
  src/main/java/com/e2i/wemeet/controller/admin/AdminMemberFixture.java
  src/main/java/com/e2i/wemeet/controller/admin/TestTokenInjectionController.java
  src/main/java/com/e2i/wemeet/controller/credential/CredentialController.java
  src/main/java/com/e2i/wemeet/controller/member/MemberController.java
  src/main/java/com/e2i/wemeet/controller/profileimage/ProfileImageController.java
  src/main/java/com/e2i/wemeet/controller/team/TeamController.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/domain/member/Preference.java
  src/main/java/com/e2i/wemeet/domain/profileimage/ProfileImage.java
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/domain/team/invitation/TeamInvitation.java
  src/main/java/com/e2i/wemeet/dto/request/team/CreateTeamRequestDto.java
  src/main/java/com/e2i/wemeet/dto/response/ResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/member/MemberPreferenceResponseDto.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/ErrorResponse.java
  src/main/java/com/e2i/wemeet/exception/badrequest/MemberHasBeenDeletedException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/TeamHasBeenDeletedException.java
  src/main/java/com/e2i/wemeet/service/member/MemberService.java
  src/main/java/com/e2i/wemeet/service/member/MemberServiceImpl.java
  src/main/java/com/e2i/wemeet/service/team/TeamService.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/main/java/com/e2i/wemeet/util/aspect/TokenInjectionAspect.java
  src/main/resources/db/migration/V2306210150__create_member.sql
  src/main/resources/db/migration/V2306211524__create_team.sql
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/controller/admin/TestTokenInjectionControllerTest.java
  src/test/java/com/e2i/wemeet/controller/credential/CredentialControllerTest.java
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
  src/test/java/com/e2i/wemeet/support/fixture/MemberFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
  src/test/java/com/e2i/wemeet/util/aspect/TokenInjectionAspectTest.java
Labels: 🛠 refactor

#77 refactor(member): refactory the member registration api
  src/main/java/com/e2i/wemeet/dto/request/member/CreateMemberRequestDto.java
  src/main/java/com/e2i/wemeet/service/member/MemberService.java
  src/main/java/com/e2i/wemeet/service/member/MemberServiceImpl.java
  src/main/java/com/e2i/wemeet/util/RandomCodeUtils.java
  src/main/java/com/e2i/wemeet/util/aspect/TokenInjectionAspect.java
  src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
  src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java
  src/test/java/com/e2i/wemeet/util/aspect/TokenInjectionAspectTest.java
Labels: 🛠 refactor

#79 refactor(test): change junit to assertj
  src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamInvitationServiceTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
Labels: 🛠 refactor
