Repository SWM-E2I/wemeet-backend, pull requests merged in 2023-08, with the labels that each got.

#86 feat(enum): Apply JPA Attribute Converter to Enum field of entity
  build.gradle
  src/main/java/com/e2i/wemeet/domain/base/BaseTimeEntity.java
  src/main/java/com/e2i/wemeet/domain/base/CreateTimeEntity.java
  src/main/java/com/e2i/wemeet/domain/base/converter/AcceptStatusConverter.java
  src/main/java/com/e2i/wemeet/domain/base/converter/AdditionalActivityConverter.java
  src/main/java/com/e2i/wemeet/domain/base/converter/CollegeTypeConverter.java
  src/main/java/com/e2i/wemeet/domain/base/converter/DrinkWithGameConverter.java
  src/main/java/com/e2i/wemeet/domain/base/converter/GenderConverter.java
  src/main/java/com/e2i/wemeet/domain/base/converter/MbtiConverter.java
  src/main/java/com/e2i/wemeet/domain/base/converter/RegionConverter.java
  src/main/java/com/e2i/wemeet/domain/code/Code.java
  src/main/java/com/e2i/wemeet/domain/code/CodePk.java
  src/main/java/com/e2i/wemeet/domain/code/GroupCode.java
  src/main/java/com/e2i/wemeet/domain/meeting/MeetingRequest.java
  src/main/java/com/e2i/wemeet/domain/meeting/data/AcceptStatus.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/domain/member/data/CollegeInfo.java
  src/main/java/com/e2i/wemeet/domain/member/data/CollegeType.java
  src/main/java/com/e2i/wemeet/domain/member/data/Mbti.java
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/domain/team/data/AdditionalActivity.java
  src/main/java/com/e2i/wemeet/domain/team/data/DrinkWithGame.java
  src/main/java/com/e2i/wemeet/domain/team/data/Region.java
  src/main/java/com/e2i/wemeet/domain/team_member/TeamMember.java
  src/main/java/com/e2i/wemeet/dto/request/member/CreateMemberRequestDto.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/badrequest/InvalidDatabaseKeyToEnumException.java
  src/main/resources/db/migration/V2306211556__create_code.sql
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/config/security/manager/CreditAuthorizationManagerTest.java
  src/test/java/com/e2i/wemeet/domain/base/converter/JpaAttributeConverterTest.java
  src/test/java/com/e2i/wemeet/service/code/CodeServiceTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
  src/test/java/com/e2i/wemeet/support/config/AbstractRepositoryUnitTest.java
  src/test/java/com/e2i/wemeet/support/config/ReflectionUtils.java
  src/test/java/com/e2i/wemeet/support/fixture/CollegeInfoFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/MeetingRequestFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/MemberFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamMemberFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/code/CodeFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/code/GroupCodeFixture.java
Labels: ✨ feat, 💻 test, 🛠 refactor

#88 refactor(image): change api request&response data
  src/main/java/com/e2i/wemeet/controller/member/MemberController.java
  src/main/java/com/e2i/wemeet/controller/profileimage/ProfileImageController.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/domain/member/data/ProfileImage.java
  src/main/java/com/e2i/wemeet/service/aws/s3/S3Service.java
  src/main/java/com/e2i/wemeet/service/aws/s3/S3ServiceImpl.java
  src/main/java/com/e2i/wemeet/service/member/MemberServiceImpl.java
  src/main/java/com/e2i/wemeet/service/member_image/MemberImageService.java
  src/main/java/com/e2i/wemeet/service/member_image/MemberImageServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
  src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java
  src/test/java/com/e2i/wemeet/service/member_image/MemberImageServiceTest.java
Labels: 🛠 refactor

#91 fix(test): make test red to green
  src/main/java/com/e2i/wemeet/domain/code/CodePk.java
  src/main/java/com/e2i/wemeet/domain/code/CodeRepository.java
  src/main/java/com/e2i/wemeet/security/model/MemberPrincipal.java
  src/main/java/com/e2i/wemeet/security/provider/SmsUserDetailsService.java
  src/main/java/com/e2i/wemeet/service/code/CodeServiceImpl.java
  src/main/java/com/e2i/wemeet/util/validator/CustomFormatValidator.java
  src/test/java/com/e2i/wemeet/config/security/filter/SmsLoginProcessingFilterTest.java
  src/test/java/com/e2i/wemeet/domain/code/CodeRepositoryTest.java
  src/test/java/com/e2i/wemeet/domain/member/MemberRepositoryTest.java
  src/test/java/com/e2i/wemeet/service/admin/TestServiceTestAuthorization.java
  src/test/java/com/e2i/wemeet/service/code/CodeServiceTest.java
  src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java
  src/test/java/com/e2i/wemeet/util/validator/CustomFormatValidatorTest.java
Labels: 🐞 fix, 💻 test

#93 fix: Add exception handler and EndPointcheckfilter to security
  src/main/java/com/e2i/wemeet/controller/GlobalExceptionController.java
  src/main/java/com/e2i/wemeet/dto/response/member/ProfileImageResponseDto.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/security/config/SecurityBeanConfig.java
  src/main/java/com/e2i/wemeet/security/config/SecurityConfig.java
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/security/filter/RequestEndPointCheckFilterTest.java
  src/test/java/com/e2i/wemeet/security/handler/DispatcherServletEndPointCheckerTest.java
  src/test/java/com/e2i/wemeet/support/config/AbstractIntegrationTest.java
Labels: 🐞 fix

#97 refactor(log): change log framework
  build.gradle
  src/main/java/com/e2i/wemeet/config/log/LogFilter.java
  src/main/java/com/e2i/wemeet/config/log/aspect/ControllerLogAspect.java
  src/main/java/com/e2i/wemeet/config/log/aspect/ServiceLogAspect.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 🖌 chore

#94 feat(log): add logging filter & AOP module
  src/main/java/com/e2i/wemeet/config/log/LogConfig.java
  src/main/java/com/e2i/wemeet/config/log/LogFilter.java
  src/main/java/com/e2i/wemeet/config/log/MdcKey.java
  src/main/java/com/e2i/wemeet/config/log/aspect/ControllerLogAspect.java
  src/main/java/com/e2i/wemeet/config/log/aspect/QueryCounterAspect.java
  src/main/java/com/e2i/wemeet/config/log/aspect/ServiceLogAspect.java
  src/main/java/com/e2i/wemeet/config/log/module/ConnectionInvocationHandler.java
  src/main/java/com/e2i/wemeet/config/log/module/PreparedStatementInvocationHandler.java
  src/main/java/com/e2i/wemeet/config/log/module/QueryCounter.java
  src/main/java/com/e2i/wemeet/config/resolver/member/MemberIdArgumentResolver.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/security/config/SecurityConfig.java
  src/main/java/com/e2i/wemeet/security/filter/JwtAuthenticationFilter.java
  src/main/resources/application.yml
  src/main/resources/log4j2.yml
  src/main/resources/logback-spring.xml
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/config/security/filter/SmsLoginProcessingFilterTest.java
  src/test/java/com/e2i/wemeet/controller/TokenControllerTest.java
  src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/support/config/AbstractControllerUnitTest.java
  src/test/java/com/e2i/wemeet/support/config/TestWebBeanConfig.java
Labels: ✨ feat

#96 test(team): add controller, service test
  src/main/java/com/e2i/wemeet/controller/team/TeamController.java
  src/main/java/com/e2i/wemeet/dto/response/team/MyTeamDetailResponseDto.java
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
  src/test/java/com/e2i/wemeet/support/fixture/MemberFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamMemberFixture.java
Labels: 💻 test, 🛠 refactor
