Repository SWM-E2I/wemeet-backend, pull requests merged in 2023-09, with the labels that each got.

#109 refactor(meeting): remove chatLink when accept meeting request
  src/main/java/com/e2i/wemeet/controller/meeting/MeetingController.java
  src/main/java/com/e2i/wemeet/domain/meeting/Meeting.java
  src/main/java/com/e2i/wemeet/service/meeting/MeetingHandleService.java
  src/main/java/com/e2i/wemeet/service/meeting/MeetingHandleServiceImpl.java
  src/main/resources/db/migration/V2308022347__create_meeting.sql
  src/test/java/com/e2i/wemeet/controller/meeting/MeetingControllerTest.java
  src/test/java/com/e2i/wemeet/service/meeting/MeetingHandleServiceImplTest.java
  src/test/java/com/e2i/wemeet/support/fixture/MeetingFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
Labels: 🛠 refactor

#112 feat(team): Add an API that can look up team details by team ID
  src/main/java/com/e2i/wemeet/controller/team/TeamController.java
  src/main/java/com/e2i/wemeet/domain/meeting/MeetingReadRepositoryImpl.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/domain/team/TeamCustomRepository.java
  src/main/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImpl.java
  src/main/java/com/e2i/wemeet/domain/team_member/TeamMember.java
  src/main/java/com/e2i/wemeet/dto/dsl/MeetingInformationDto.java
  src/main/java/com/e2i/wemeet/dto/dsl/MeetingRequestInformationDto.java
  src/main/java/com/e2i/wemeet/dto/dsl/TeamInformationDto.java
  src/main/java/com/e2i/wemeet/dto/dsl/TeamMemberInformationDto.java
  src/main/java/com/e2i/wemeet/dto/response/LeaderResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/meeting/AcceptedMeetingResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/meeting/LeaderResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/meeting/ReceivedMeetingResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/meeting/SentMeetingResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamDetailResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamMemberResponseDto.java
  src/main/java/com/e2i/wemeet/service/team/TeamService.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/test/java/com/e2i/wemeet/controller/meeting/MeetingControllerTest.java
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImplTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceImplTest.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
Labels: ✨ feat

#111 feat(hear): add heart api
  src/main/java/com/e2i/wemeet/controller/heart/HeartController.java
  src/main/java/com/e2i/wemeet/controller/meeting/MeetingController.java
  src/main/java/com/e2i/wemeet/controller/team/TeamController.java
  src/main/java/com/e2i/wemeet/domain/heart/Heart.java
  src/main/java/com/e2i/wemeet/domain/heart/HeartCustomRepository.java
  src/main/java/com/e2i/wemeet/domain/heart/HeartCustomRepositoryImpl.java
  src/main/java/com/e2i/wemeet/domain/heart/HeartRepository.java
  src/main/java/com/e2i/wemeet/domain/like/LikeRepository.java
  src/main/java/com/e2i/wemeet/domain/meeting/Meeting.java
  src/main/java/com/e2i/wemeet/domain/meeting/MeetingReadRepositoryImpl.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/domain/team/TeamCustomRepository.java
  src/main/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImpl.java
  src/main/java/com/e2i/wemeet/domain/team_member/TeamMember.java
  src/main/java/com/e2i/wemeet/dto/dsl/HeartTeamData.java
  src/main/java/com/e2i/wemeet/dto/dsl/MeetingInformationDto.java
  src/main/java/com/e2i/wemeet/dto/dsl/MeetingRequestInformationDto.java
  src/main/java/com/e2i/wemeet/dto/dsl/TeamInformationDto.java
  src/main/java/com/e2i/wemeet/dto/dsl/TeamMemberInformationDto.java
  src/main/java/com/e2i/wemeet/dto/response/LeaderResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/heart/ReceivedHeartResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/heart/SentHeartResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/meeting/AcceptedMeetingResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/meeting/LeaderResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/meeting/ReceivedMeetingResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/meeting/SentMeetingResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamDetailResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamMemberResponseDto.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/badrequest/HeartAlreadyExistsException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/NotSendToOwnTeamException.java
  src/main/java/com/e2i/wemeet/security/handler/DispatcherServletEndPointChecker.java
  src/main/java/com/e2i/wemeet/service/heart/HeartService.java
  src/main/java/com/e2i/wemeet/service/heart/HeartServiceImpl.java
  src/main/java/com/e2i/wemeet/service/meeting/MeetingHandleService.java
  src/main/java/com/e2i/wemeet/service/meeting/MeetingHandleServiceImpl.java
  src/main/java/com/e2i/wemeet/service/team/TeamService.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/main/resources/db/migration/V2308012303__create_heart.sql
  src/main/resources/db/migration/V2308022347__create_meeting.sql
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/controller/heart/HeartControllerTest.java
  src/test/java/com/e2i/wemeet/controller/meeting/MeetingControllerTest.java
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/domain/heart/HeartCustomRepositoryTest.java
  src/test/java/com/e2i/wemeet/domain/heart/HeartRepositoryTest.java
  src/test/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImplTest.java
  src/test/java/com/e2i/wemeet/service/heart/HeartServiceTest.java
  src/test/java/com/e2i/wemeet/service/meeting/MeetingHandleServiceImplTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceImplTest.java
  src/test/java/com/e2i/wemeet/support/config/AbstractControllerUnitTest.java
  src/test/java/com/e2i/wemeet/support/fixture/MeetingFixture.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
Labels: ✨ feat

#114 refactor(team): add team leader data to api response
  src/main/java/com/e2i/wemeet/domain/team/suggestion/SuggestionRepositoryImpl.java
  src/main/java/com/e2i/wemeet/dto/response/team/MyTeamDetailResponseDto.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
  src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
Labels: 🛠 refactor

#115 docs: Add an open spec specification for the swagger ui
  src/main/java/com/e2i/wemeet/config/log/LogExceptionPattern.java
  src/main/java/com/e2i/wemeet/config/log/LogFilter.java
  src/main/java/com/e2i/wemeet/controller/admin/TestTokenInjectionController.java
  src/main/java/com/e2i/wemeet/controller/credential/CredentialController.java
  src/main/java/com/e2i/wemeet/controller/swagger/SwaggerUiController.java
  src/main/java/com/e2i/wemeet/controller/team/TeamController.java
  src/main/java/com/e2i/wemeet/domain/meeting/MeetingReadRepositoryImpl.java
  src/main/java/com/e2i/wemeet/domain/team/TeamCustomRepository.java
  src/main/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImpl.java
  src/main/java/com/e2i/wemeet/dto/dsl/TeamInformationDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamDetailResponseDto.java
  src/main/java/com/e2i/wemeet/service/team/TeamService.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/main/resources/static/swagger-ui/sampleAuth.yaml
  src/main/resources/static/swagger-ui/testController.yaml
  src/test/java/com/e2i/wemeet/config/log/LogExceptionPatternTest.java
  src/test/java/com/e2i/wemeet/config/security/filter/RefreshTokenProcessingFilterTest.java
  src/test/java/com/e2i/wemeet/controller/TokenControllerTest.java
  src/test/java/com/e2i/wemeet/controller/credential/CredentialControllerTest.java
  src/test/java/com/e2i/wemeet/controller/heart/HeartControllerTest.java
  src/test/java/com/e2i/wemeet/controller/meeting/MeetingControllerTest.java
  src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
  src/test/java/com/e2i/wemeet/controller/suggestion/SuggestionControllerTest.java
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/domain/meeting/MeetingReadRepositoryImplTest.java
  src/test/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImplTest.java
  src/test/java/com/e2i/wemeet/service/meeting/MeetingHandleServiceImplTest.java
  src/test/java/com/e2i/wemeet/service/team/TeamServiceImplTest.java
Labels: 📚 docs

#116 refactor(token): change token refresh logic
  src/main/java/com/e2i/wemeet/controller/GlobalExceptionController.java
  src/main/java/com/e2i/wemeet/domain/member/MemberRepository.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/token/NotEqualRoleToTokenException.java
  src/main/java/com/e2i/wemeet/security/config/SecurityBeanConfig.java
  src/main/java/com/e2i/wemeet/security/filter/RefreshTokenProcessingFilter.java
  src/main/java/com/e2i/wemeet/security/manager/IsManager.java
  src/main/java/com/e2i/wemeet/security/model/MemberPrincipal.java
  src/main/java/com/e2i/wemeet/service/admin/TokenAuthorizationService.java
  src/main/java/com/e2i/wemeet/util/aspect/TokenValidationAspect.java
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/config/security/filter/RefreshTokenProcessingFilterTest.java
  src/test/java/com/e2i/wemeet/controller/heart/HeartControllerTest.java
  src/test/java/com/e2i/wemeet/service/admin/TestServiceTestAuthorization.java
Labels: 🛠 refactor

#117 refactor(team): add some fields to find team detail query response
  src/main/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImpl.java
  src/main/java/com/e2i/wemeet/dto/dsl/TeamInformationDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamDetailResponseDto.java
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImplTest.java
Labels: 🛠 refactor

#121 refactor(image): change image url from s3 to cloudFront
  src/main/java/com/e2i/wemeet/service/member_image/MemberImageServiceImpl.java
  src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
Labels: 🛠 refactor

#122 refactor(heart): change api response to list
  src/main/java/com/e2i/wemeet/controller/heart/HeartController.java
  src/main/java/com/e2i/wemeet/dto/response/heart/ReceivedHeartResponseDto.java
  src/main/java/com/e2i/wemeet/dto/response/heart/SentHeartResponseDto.java
  src/main/java/com/e2i/wemeet/service/heart/HeartService.java
  src/main/java/com/e2i/wemeet/service/heart/HeartServiceImpl.java
  src/test/java/com/e2i/wemeet/controller/heart/HeartControllerTest.java
  src/test/java/com/e2i/wemeet/service/heart/HeartServiceTest.java
Labels: 🛠 refactor

#126 refactor(meeting): Change meeting subscriptions to prevent duplicate
  src/main/java/com/e2i/wemeet/domain/meeting/MeetingRepository.java
  src/main/java/com/e2i/wemeet/domain/meeting/MeetingRequestRepository.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/badrequest/DuplicateMeetingRequestException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/MeetingAlreadyExistException.java
  src/main/java/com/e2i/wemeet/service/meeting/MeetingHandleServiceImpl.java
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/domain/meeting/MeetingRepositoryTest.java
  src/test/java/com/e2i/wemeet/domain/meeting/MeetingRequestRepositoryTest.java
  src/test/java/com/e2i/wemeet/service/meeting/MeetingHandleServiceImplTest.java
Labels: 🛠 refactor

#127 refactor(team): add chatlink to read team detail api
  src/main/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImpl.java
  src/main/java/com/e2i/wemeet/dto/dsl/TeamInformationDto.java
  src/main/java/com/e2i/wemeet/dto/response/team/TeamDetailResponseDto.java
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java
  src/test/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImplTest.java
Labels: 🛠 refactor

#132 E2 i 131 rim/added function to save service aggrement data to api that create member
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/dto/request/member/CreateMemberRequestDto.java
  src/main/java/com/e2i/wemeet/security/provider/SmsUserDetailsService.java
  src/main/java/com/e2i/wemeet/util/validator/bean/BooleanTypeValid.java
  src/main/java/com/e2i/wemeet/util/validator/module/BooleanTypeValidator.java
  src/main/resources/db/migration/V2306210150__create_member.sql
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
  src/test/java/com/e2i/wemeet/support/fixture/MemberFixture.java
Labels: ✨ feat
