Repository SWM-E2I/wemeet-backend, pull requests merged in 2023-06, with the labels that each got.

#2 build(ci): use sonarcloud as static analysis tool with github actions
  .github/workflows/ci.yml
  build.gradle
Labels: 🚀 build

#3 build(ci): add develop branch to ci workflow
  .github/workflows/ci.yml
Labels: 🚀 build

#6 build(gradle): add settings for flyway
  build.gradle
  src/main/resources/application.yml
Labels: 🚀 build

#7 feat(error): add exception handler and CustomException
  src/main/java/com/e2i/wemeet/config/h2/H2DatabaseRunnerConfig.java
  src/main/java/com/e2i/wemeet/controller/GlobalExceptionController.java
  src/main/java/com/e2i/wemeet/exception/CustomException.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/ErrorResponse.java
  src/main/java/com/e2i/wemeet/exception/badrequest/InvalidSmsCredentialException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/InvalidValueException.java
  src/main/java/com/e2i/wemeet/exception/internal/InternalServerException.java
  src/main/java/com/e2i/wemeet/exception/notfound/NotFoundException.java
  src/main/java/com/e2i/wemeet/exception/unauthorized/UnAuthorizedException.java
  src/main/resources/messages.properties
Labels: ✨ feat

#10 feat(db): add entity
  src/main/java/com/e2i/wemeet/domain/base/BaseTimeEntity.java
  src/main/java/com/e2i/wemeet/domain/code/Code.java
  src/main/java/com/e2i/wemeet/domain/code/CodePk.java
  src/main/java/com/e2i/wemeet/domain/code/CodeRepository.java
  src/main/java/com/e2i/wemeet/domain/code/GroupCode.java
  src/main/java/com/e2i/wemeet/domain/code/GroupCodeRepository.java
  src/main/java/com/e2i/wemeet/domain/member/CollegeInfo.java
  src/main/java/com/e2i/wemeet/domain/member/Gender.java
  src/main/java/com/e2i/wemeet/domain/member/Mbti.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/domain/member/MemberRepository.java
  src/main/java/com/e2i/wemeet/domain/member/Preference.java
  src/main/java/com/e2i/wemeet/domain/member_interest/MemberInterest.java
  src/main/java/com/e2i/wemeet/domain/member_interest/MemberInterestRepository.java
  src/main/java/com/e2i/wemeet/domain/member_preference_meeting_type/MemberPreferenceMeetingType.java
  src/main/java/com/e2i/wemeet/domain/member_preference_meeting_type/MemberPreferenceMeetingTypeRepository.java
  src/main/java/com/e2i/wemeet/domain/profile_image/ProfileImage.java
  src/main/java/com/e2i/wemeet/domain/profile_image/ProfileImageRepository.java
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/domain/team/TeamRepository.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/resources/db/migration/V2306210150__create_member.sql
  src/main/resources/db/migration/V2306211449__create_profileImage.sql
  src/main/resources/db/migration/V2306211524__create_team.sql
  src/main/resources/db/migration/V2306211556__create_code.sql
  src/main/resources/db/migration/V2306211651__create_memberInterest.sql
  src/main/resources/db/migration/V2306211732__create_memberPreferenceMeetingType.sql
  src/main/resources/messages.properties
Labels: ✨ feat

#13 build(checkstyle): add checkstyle plugin
  build.gradle
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  config/checkstyle/suppressions_1_2.dtd
  config/intellij-java-google-style.xml
Labels: 🚀 build

#16 style(checkstyle): change code format following checkstyle rule
  src/main/java/com/e2i/wemeet/WemeetApplication.java
  src/main/java/com/e2i/wemeet/config/h2/H2DatabaseRunnerConfig.java
  src/main/java/com/e2i/wemeet/controller/GlobalExceptionController.java
  src/main/java/com/e2i/wemeet/domain/base/BaseTimeEntity.java
  src/main/java/com/e2i/wemeet/domain/code/Code.java
  src/main/java/com/e2i/wemeet/domain/code/CodePk.java
  src/main/java/com/e2i/wemeet/domain/code/GroupCode.java
  src/main/java/com/e2i/wemeet/domain/member/CollegeInfo.java
  src/main/java/com/e2i/wemeet/domain/member/Gender.java
  src/main/java/com/e2i/wemeet/domain/member/Mbti.java
  src/main/java/com/e2i/wemeet/domain/member/Member.java
  src/main/java/com/e2i/wemeet/domain/member/Preference.java
  src/main/java/com/e2i/wemeet/domain/member_preference_meeting_type/MemberPreferenceMeetingType.java
  src/main/java/com/e2i/wemeet/domain/member_preference_meeting_type/MemberPreferenceMeetingTypeRepository.java
  src/main/java/com/e2i/wemeet/domain/memberinterest/MemberInterest.java
  src/main/java/com/e2i/wemeet/domain/memberinterest/MemberInterestRepository.java
  src/main/java/com/e2i/wemeet/domain/memberpreferencemeetingtype/MemberPreferenceMeetingType.java
  src/main/java/com/e2i/wemeet/domain/memberpreferencemeetingtype/MemberPreferenceMeetingTypeRepository.java
  src/main/java/com/e2i/wemeet/domain/profile_image/ProfileImage.java
  src/main/java/com/e2i/wemeet/domain/profileimage/ProfileImage.java
  src/main/java/com/e2i/wemeet/domain/profileimage/ProfileImageRepository.java
  src/main/java/com/e2i/wemeet/domain/team/Team.java
  src/main/java/com/e2i/wemeet/exception/CustomException.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/exception/ErrorResponse.java
  src/main/java/com/e2i/wemeet/exception/badrequest/InvalidSmsCredentialException.java
  src/main/java/com/e2i/wemeet/exception/badrequest/InvalidValueException.java
  src/main/java/com/e2i/wemeet/exception/internal/InternalServerException.java
  src/main/java/com/e2i/wemeet/exception/unauthorized/UnAuthorizedException.java
  src/test/java/com/e2i/wemeet/WemeetApplicationTests.java
Labels: 🎨 style

#17 feat(awsSns): add aws sns config
  .gitignore
  build.gradle
  config/checkstyle/suppressions.xml
  src/main/java/com/e2i/wemeet/config/aws/AwsSnsConfig.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/service/aws/AwsCredentialService.java
  src/main/java/com/e2i/wemeet/service/aws/AwsSnsService.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/service/aws/AwsCredentialServiceTest.java
  src/test/java/com/e2i/wemeet/service/aws/AwsSnsServiceTest.java
Labels: ✨ feat

#24 feat(awsS3): add S3 config
  build.gradle
  src/main/java/com/e2i/wemeet/config/WebConfig.java
  src/main/java/com/e2i/wemeet/config/aws/AwsS3Config.java
  src/main/java/com/e2i/wemeet/exception/ErrorCode.java
  src/main/java/com/e2i/wemeet/service/aws/s3/AwsS3CredentialService.java
  src/main/java/com/e2i/wemeet/service/aws/s3/AwsS3Service.java
  src/main/resources/messages.properties
  src/test/java/com/e2i/wemeet/service/aws/s3/AwsS3CredentialServiceTest.java
  src/test/java/com/e2i/wemeet/service/aws/s3/AwsS3ServiceTest.java
Labels: ✨ feat
